[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[project]
name = "simnexus"
version = "1.2.1"
description = "A Python module for modelling complex simulation workflows."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
authors = [
  { name = "Willem", email = "willem4540@gmail.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.9"
dependencies = [
    "numpy>=1.21",
    "pandas>=1.3",
    "Jinja2>=3.0",
    "dynakw>=1.3",
    "lasso-python>=2.0",
]


[project.urls]
Homepage = "https://github.com/WillemJR/simnexus"


[project.optional-dependencies]
remote = [
    "grpcio>=1.50",
    "grpcio-tools>=1.50",
]
dyna = [
    "lasso-dyna",
    "dynakw",
]
plot = [
    "matplotlib>=3.5",
]
progress = [
    "tqdm>=4.60",
]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["simnexus*"]
