# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from simnexus.protos import remote_actions_pb2 as simnexus_dot_protos_dot_remote__actions__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in simnexus/protos/remote_actions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimNexusRemoteStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAction = channel.unary_unary(
                '/simnexus.SimNexusRemote/RunAction',
                request_serializer=simnexus_dot_protos_dot_remote__actions__pb2.ActionRequest.SerializeToString,
                response_deserializer=simnexus_dot_protos_dot_remote__actions__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.GetAvailableActions = channel.unary_unary(
                '/simnexus.SimNexusRemote/GetAvailableActions',
                request_serializer=simnexus_dot_protos_dot_remote__actions__pb2.Empty.SerializeToString,
                response_deserializer=simnexus_dot_protos_dot_remote__actions__pb2.AvailableActionsResponse.FromString,
                _registered_method=True)


class SimNexusRemoteServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvailableActions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimNexusRemoteServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RunAction,
                    request_deserializer=simnexus_dot_protos_dot_remote__actions__pb2.ActionRequest.FromString,
                    response_serializer=simnexus_dot_protos_dot_remote__actions__pb2.ActionResponse.SerializeToString,
            ),
            'GetAvailableActions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvailableActions,
                    request_deserializer=simnexus_dot_protos_dot_remote__actions__pb2.Empty.FromString,
                    response_serializer=simnexus_dot_protos_dot_remote__actions__pb2.AvailableActionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simnexus.SimNexusRemote', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simnexus.SimNexusRemote', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimNexusRemote(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simnexus.SimNexusRemote/RunAction',
            simnexus_dot_protos_dot_remote__actions__pb2.ActionRequest.SerializeToString,
            simnexus_dot_protos_dot_remote__actions__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvailableActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simnexus.SimNexusRemote/GetAvailableActions',
            simnexus_dot_protos_dot_remote__actions__pb2.Empty.SerializeToString,
            simnexus_dot_protos_dot_remote__actions__pb2.AvailableActionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
