syntax = "proto3";

package simnexus;

service SimNexusRemote {
  rpc RunAction (ActionRequest) returns (ActionResponse) {}
  rpc GetAvailableActions (Empty) returns (AvailableActionsResponse) {}
}

message Empty {}

message ActionInfo {
  string name = 1;
  string description = 2;
}

message AvailableActionsResponse {
  repeated ActionInfo actions = 1;
}

message File {
  string name = 1;
  bytes content = 2;
}

message ActionRequest {
  string action_name = 1;
  bytes pickled_val_dict = 3;
  repeated File input_files = 4;
  repeated string output_patterns = 5;
  string target_action_name = 6; // name of action already on server
}

message ActionResponse {
  bool success = 1;
  string error_message = 2;
  bytes pickled_results = 3; // The result dictionary
  repeated File output_files = 4;
}
