# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: simflow/protos/remote_actions.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'simflow/protos/remote_actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#simflow/protos/remote_actions.proto\x12\x07simflow\"%\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\"\x93\x01\n\rActionRequest\x12\x13\n\x0b\x61\x63tion_name\x18\x01 \x01(\t\x12\x16\n\x0epickled_action\x18\x02 \x01(\x0c\x12\x18\n\x10pickled_val_dict\x18\x03 \x01(\x0c\x12\"\n\x0binput_files\x18\x04 \x03(\x0b\x32\r.simflow.File\x12\x17\n\x0foutput_patterns\x18\x05 \x03(\t\"v\n\x0e\x41\x63tionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x17\n\x0fpickled_results\x18\x03 \x01(\x0c\x12#\n\x0coutput_files\x18\x04 \x03(\x0b\x32\r.simflow.File2O\n\rSimFlowRemote\x12>\n\tRunAction\x12\x16.simflow.ActionRequest\x1a\x17.simflow.ActionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simflow.protos.remote_actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILE']._serialized_start=48
  _globals['_FILE']._serialized_end=85
  _globals['_ACTIONREQUEST']._serialized_start=88
  _globals['_ACTIONREQUEST']._serialized_end=235
  _globals['_ACTIONRESPONSE']._serialized_start=237
  _globals['_ACTIONRESPONSE']._serialized_end=355
  _globals['_SIMFLOWREMOTE']._serialized_start=357
  _globals['_SIMFLOWREMOTE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
